project_id = "ysutwfzdpfvziasxbbvn"

[functions.create-solana-wallet]
verify_jwt = true

[functions.mint-land-nft]
verify_jwt = true

[functions.nearby-tasks]
verify_jwt = false

[functions.qr-claim]
verify_jwt = true

[functions.selfie-submit]
verify_jwt = true

[functions.generate-location-task]
verify_jwt = true

[functions.verify-photo-task]
verify_jwt = true

[functions.request-nonce]
verify_jwt = true

[functions.join-task]
verify_jwt = true

[functions.admin-generate-tasks]
verify_jwt = true

[functions.get-tasks]
verify_jwt = false

[functions.admin-publish-task]
verify_jwt = true

[functions.get-task-share]
verify_jwt = false

[functions.task-generation-worker]
verify_jwt = false